# Generated by Django 5.0 on 2024-01-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('page_count', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('shelf_location', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
                ('is_in_stock', models.BooleanField(default=True)),
                ('date_checked_out', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
