# Generated by Django 5.0 on 2024-02-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_add_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=50, verbose_name='Publisher')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('pageCount', models.IntegerField(default=10, verbose_name='Page Count')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('shelfLocation', models.CharField(max_length=50, verbose_name='Shelf Location')),
                ('publishedDate', models.DateField(verbose_name='Published Date')),
                ('isInStock', models.BooleanField(default=True, verbose_name='is in stock')),
                ('dateCheckedOut', models.DateField(auto_now=True, verbose_name='Date Checked Out')),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Library',
                'db_table': 'library',
            },
        ),
    ]
